# Generated by Django 3.2.5 on 2021-07-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=100)),
                ('profilename', models.CharField(max_length=1000)),
                ('helpfulness', models.CharField(max_length=10)),
                ('score', models.FloatField()),
                ('date', models.DateTimeField()),
                ('summary', models.CharField(max_length=2000)),
            ],
        ),
    ]
